// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8A7chbAtAXqwEHUpBmwXg7EFHUtGkWEk',
    appId: '1:130320733065:web:0c08c31bcc08c84b154758',
    messagingSenderId: '130320733065',
    projectId: 'gstease-2096c',
    authDomain: 'gstease-2096c.firebaseapp.com',
    storageBucket: 'gstease-2096c.firebasestorage.app',
    measurementId: 'G-VRXMDP4DTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA29sD5Bd6jIl0_vxWBxKYWTQ2RFRKmWA',
    appId: '1:130320733065:android:0f86359570330416154758',
    messagingSenderId: '130320733065',
    projectId: 'gstease-2096c',
    storageBucket: 'gstease-2096c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQP70kzdPW0XMEwtBswj1vZYKtUhaVCxM',
    appId: '1:130320733065:ios:706bd4cf8f8f19b7154758',
    messagingSenderId: '130320733065',
    projectId: 'gstease-2096c',
    storageBucket: 'gstease-2096c.firebasestorage.app',
    iosBundleId: 'com.example.gstease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQP70kzdPW0XMEwtBswj1vZYKtUhaVCxM',
    appId: '1:130320733065:ios:706bd4cf8f8f19b7154758',
    messagingSenderId: '130320733065',
    projectId: 'gstease-2096c',
    storageBucket: 'gstease-2096c.firebasestorage.app',
    iosBundleId: 'com.example.gstease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8A7chbAtAXqwEHUpBmwXg7EFHUtGkWEk',
    appId: '1:130320733065:web:a18653428c60a16c154758',
    messagingSenderId: '130320733065',
    projectId: 'gstease-2096c',
    authDomain: 'gstease-2096c.firebaseapp.com',
    storageBucket: 'gstease-2096c.firebasestorage.app',
    measurementId: 'G-5KSK1E1EFB',
  );
}
